// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itxzazsfjerzxsvlcdkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0eHphenNmamVyenhzdmxjZGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjcwODIsImV4cCI6MjA3MjE0MzA4Mn0.bhor8pU2t5yryYEAm8otwc-CSlE7E-exBisMIBagRvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});